cc_library(
    name = "window",
    srcs = ["window.cpp"],
    hdrs = ["window.hpp"],
    visibility = ["//heavy_light_transport:__subpackages__"],
    deps = [
        "//third_party/glad",
        "//third_party/glfw",
    ],
)
