cc_library(
    name = "application",
    srcs = ["application.cpp"],
    hdrs = ["application.hpp"],
    deps = ["//heavy_light_transport/core"],
    visibility = ["//heavy_light_transport:__subpackages__"],
)
